name: Web CI
on:
  pull_request:
    branches: ["main"]
jobs:
  web-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Mise install
        uses: jdx/mise-action@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./web
      - name: Check code format
        run: pnpm run format:check
        working-directory: ./web
